# Site settings
title: Ali Taylor | Product + UX Designer
email: hello@alastairtaylor.com
description: Im a Product + UX Designer currently working at Booking.com.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alitaylor.nl" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

